repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
# repo: https://github.com/pre-commit/mirrors-pytest
#  rev: v1.32.0
#  hooks:
#  - id: pytest
#    args: ['-k', 'not integration']  # Example: exclude integration tests
