[tool.poetry]
name = "weather"
version = "0.1.0"
description = ""
authors = ["miguel <myguel.ra@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.109.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
